services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsCourses\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
   
  NITSAN\NsCourses\Event\EventListener:  
    tags:
      - name: event.listener
        identifier: 'ns_faq/extension-activated'

  
  NITSAN\NsCourses\Event\CourseCreatedEventListener:
    autowire: true
    autoconfigure: true
    public: true
    

  NITSAN\NsCourses\Event\StudentCreatedEmailListener:
    autowire: true
    autoconfigure: true
    public: true


  NITSAN\NsCourses\Controller\StudentsController:
    arguments:
      $eventDispatcher: '@Psr\EventDispatcher\EventDispatcherInterface'
      $studentsRepository: '@NITSAN\NsCourses\Domain\Repository\StudentsRepository'
      $courseRepository: '@NITSAN\NsCourses\Domain\Repository\CourseRepository'
      $persistenceManager: '@TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager'


 
